export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  BATCH_NOT_DISPATCHABLE: "BATCH_NOT_DISPATCHABLE",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  SAFETY_STOCK_BREACH: "SAFETY_STOCK_BREACH",
  CONCURRENT_CLAIM_FAILED: "CONCURRENT_CLAIM_FAILED",
  DISPATCH_NOT_FOUND: "DISPATCH_NOT_FOUND",
  DISPATCH_NOT_ACTIONABLE: "DISPATCH_NOT_ACTIONABLE",
  REASON_REQUIRED: "REASON_REQUIRED"
} as const;
