/** 业务错误码：controller 据此映射 HTTP 状态与响应体。 */
export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  BATCH_NOT_TRANSFERABLE: 'BATCH_NOT_TRANSFERABLE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  SAFETY_STOCK_VIOLATION: 'SAFETY_STOCK_VIOLATION',
  RELEASE_REASON_REQUIRED: 'RELEASE_REASON_REQUIRED',
  ORDER_STATE_INVALID: 'ORDER_STATE_INVALID',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});
